/*init global_sequence*/
DROP SEQUENCE IF EXISTS global_sequence CASCADE;
CREATE SEQUENCE global_sequence AS INTEGER START WITH 1000000;

/*init users table*/
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users
(
  id                         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_sequence,

  name                       VARCHAR(255) NOT NULL,
  password                   VARCHAR(255) NOT NULL,
  email                      VARCHAR(255) NOT NULL,
  max_hours_per_day          INTEGER DEFAULT 8,
  registered_date_and_time   TIMESTAMP DEFAULT now(),

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS main_goals CASCADE;
CREATE TABLE main_goals
(
  id                         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_sequence,
  user_id                    INTEGER /*NOT NULL*/,

  description                VARCHAR(255) NOT NULL,
  UNIQUE (description),

  PRIMARY KEY (id),
  FOREIGN KEY (user_id)   REFERENCES users(id) ON DELETE CASCADE
);

/*init notations table*/
DROP TABLE if EXISTS notations CASCADE;
CREATE TABLE notations(
  id                      INTEGER GENERATED BY DEFAULT AS SEQUENCE global_sequence,
  user_id                 INTEGER /*NOT NULL*/,

  name                    VARCHAR(255) NOT NULL,
  url                     VARCHAR(255) NOT NULL,
  description             VARCHAR(255) NOT NULL,
  hours                   INTEGER DEFAULT 2,
  created_date_and_time   TIMESTAMP DEFAULT now(),

  PRIMARY KEY (id),
  FOREIGN KEY (user_id)   REFERENCES users(id) ON DELETE CASCADE
);